name: Deploy React + Node App to AWS (Monorepo)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
      EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install deps for all workspaces (client + server)
      - name: Install dependencies
        run: npm ci

      # ---- FRONTEND DEPLOYMENT ----
      - name: Build React app
        run: npm run build --workspace=client

      - name: Deploy frontend to S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: ${{ env.S3_BUCKET }}
          region: ${{ env.AWS_REGION }}
          source: ./client/build
          delete: true

      - name: Invalidate CloudFront cache
        uses: aws-actions/cloudfront-invalidate-cache@v1
        with:
          distribution-id: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: "/*"

      # ---- BACKEND DEPLOYMENT ----
      - name: Zip backend for Elastic Beanstalk
        run: |
          cd server
          zip -r ../server.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.EB_APP_NAME }}
          environment_name: ${{ env.EB_ENV_NAME }}
          version_label: v-${{ github.run_number }}
          region: ${{ env.AWS_REGION }}
          deployment_package: server.zip